Repository NTTTT-NFT-Ticket-Trading-Town/NTTTT-BE, pull requests merged in 2023-05, with the labels that each got.

#14 feat: 스웨거 설정 추가,
  build.gradle
  src/main/java/com/knu/ntttt_server/core/config/SwaggerConfig.java
  src/main/java/com/knu/ntttt_server/core/controller/HelloController.java
  src/main/java/com/knu/ntttt_server/token/controller/TokenController.java
  src/main/java/com/knu/ntttt_server/user/config/SecurityConfig.java
  src/main/java/com/knu/ntttt_server/user/controller/UserController.java
  src/main/resources/application-local.yml
  src/main/resources/application.yml
Labels: new feature

#15 PaymentController 추가
  src/main/java/com/knu/ntttt_server/token/controller/PaymentController.java
  src/main/java/com/knu/ntttt_server/token/service/PaymentService.java
  src/main/java/com/knu/ntttt_server/token/service/PaymentServiceImpl.java
  src/main/java/com/knu/ntttt_server/user/service/UserService.java
Labels: new feature

#20 fix: user 테이블 H2 예약어 겹침 문제로 이름 변경
  src/main/java/com/knu/ntttt_server/user/model/User.java
Labels: fix

#19 Artist, Token 엔티티에 ratio 필드 추가, 토큰 조회 시 관련된 artist 정보 조회
  src/main/java/com/knu/ntttt_server/token/dto/TokenDto.java
  src/main/java/com/knu/ntttt_server/token/model/Artist.java
  src/main/java/com/knu/ntttt_server/token/model/Image.java
  src/main/java/com/knu/ntttt_server/token/model/Token.java
Labels: modification

#21 feature: 도커파일, 배포 스크립트 추가
  .gitignore
  deploy.sh
  docker-compose.yml
  dockerfile
  gradlew
  src/main/resources/application-dev.yml
Labels: new feature

#24 feat: 유저 인증 관련 기능 추가 (JWT 필터, 로그인, CurrentUser)
  build.gradle
  lombok.config
  src/main/java/com/knu/ntttt_server/core/annotation/CurrentUser.java
  src/main/java/com/knu/ntttt_server/user/config/SecurityConfig.java
  src/main/java/com/knu/ntttt_server/user/controller/UserController.java
  src/main/java/com/knu/ntttt_server/user/model/Authority.java
  src/main/java/com/knu/ntttt_server/user/model/User.java
  src/main/java/com/knu/ntttt_server/user/security/CustomUserDetailsService.java
  src/main/java/com/knu/ntttt_server/user/security/JwtAuthenticationFilter.java
  src/main/java/com/knu/ntttt_server/user/security/JwtService.java
  src/main/java/com/knu/ntttt_server/user/service/UserService.java
  src/main/resources/application.yml
  src/test/java/com/knu/ntttt_server/user/service/JwtServiceTest.java
Labels: new feature

#25 아티스트 선택 API 추가, 선택한 아티스트 이름 조회 추가
  src/main/java/com/knu/ntttt_server/user/controller/UserController.java
  src/main/java/com/knu/ntttt_server/user/dto/UserArtistDto.java
  src/main/java/com/knu/ntttt_server/user/model/UserArtist.java
  src/main/java/com/knu/ntttt_server/user/repository/UserArtistRepository.java
  src/main/java/com/knu/ntttt_server/user/service/UserArtistService.java
Labels: new feature

#26 feat: 가챠 토큰 조회, 가챠 토큰 실행 기능 추가
  src/main/java/com/knu/ntttt_server/core/exception/CommonExceptionHandler.java
  src/main/java/com/knu/ntttt_server/core/response/ResultCode.java
  src/main/java/com/knu/ntttt_server/token/controller/GachaTokenController.java
  src/main/java/com/knu/ntttt_server/token/controller/TokenController.java
  src/main/java/com/knu/ntttt_server/token/dto/ArtistDto.java
  src/main/java/com/knu/ntttt_server/token/dto/TokenDto.java
  src/main/java/com/knu/ntttt_server/token/model/Artist.java
  src/main/java/com/knu/ntttt_server/token/model/Event.java
  src/main/java/com/knu/ntttt_server/token/model/Token.java
  src/main/java/com/knu/ntttt_server/token/model/UserGachaToken.java
  src/main/java/com/knu/ntttt_server/token/repository/TokenRepository.java
  src/main/java/com/knu/ntttt_server/token/repository/UserGachaTokenRepository.java
  src/main/java/com/knu/ntttt_server/token/service/GachaService.java
  src/main/java/com/knu/ntttt_server/token/service/GachaServiceImpl.java
  src/main/java/com/knu/ntttt_server/token/service/TokenService.java
  src/main/java/com/knu/ntttt_server/token/service/TokenServiceImpl.java
  src/main/java/com/knu/ntttt_server/user/model/User.java
  src/main/java/com/knu/ntttt_server/user/model/UserArtist.java
  src/main/java/com/knu/ntttt_server/user/repository/UserArtistRepository.java
  src/main/resources/application.yml
Labels: new feature

#27 사용자 소유 토큰, 선택 아티스트 조회
  src/main/java/com/knu/ntttt_server/token/controller/TokenController.java
  src/main/java/com/knu/ntttt_server/token/dto/ArtistDto.java
  src/main/java/com/knu/ntttt_server/token/dto/TokenDto.java
  src/main/java/com/knu/ntttt_server/token/repository/TokenRepository.java
  src/main/java/com/knu/ntttt_server/token/service/TokenService.java
  src/main/java/com/knu/ntttt_server/token/service/TokenServiceImpl.java
  src/main/java/com/knu/ntttt_server/user/controller/UserController.java
  src/main/java/com/knu/ntttt_server/user/repository/UserArtistRepository.java
  src/main/java/com/knu/ntttt_server/user/service/UserPageService.java
Labels: new feature

#29 fix: 로그인 get mapping-> post mapping
  src/main/java/com/knu/ntttt_server/user/controller/UserController.java
Labels: fix

#33 hotfix: event 엔티티 반환하면 lazy loading 문제로 json 오류나서 dto 반환으로 수정
  src/main/java/com/knu/ntttt_server/token/dto/EventDto.java
  src/main/java/com/knu/ntttt_server/token/dto/TokenDto.java
Labels: fix

#32 hotfix: 가챠 잘못된 로직 수정, Cors 임시 전체 허용으로 수정
  src/main/java/com/knu/ntttt_server/token/controller/ArtistController.java
  src/main/java/com/knu/ntttt_server/token/controller/EventController.java
  src/main/java/com/knu/ntttt_server/token/controller/GachaTokenController.java
  src/main/java/com/knu/ntttt_server/token/controller/PaymentController.java
  src/main/java/com/knu/ntttt_server/token/controller/TokenController.java
  src/main/java/com/knu/ntttt_server/token/service/GachaServiceImpl.java
  src/main/java/com/knu/ntttt_server/user/controller/UserController.java
Labels: fix

#36 Fix: 랜덤 가챠토큰 로직 수정
  src/main/java/com/knu/ntttt_server/token/repository/TokenRepository.java
  src/main/java/com/knu/ntttt_server/token/service/GachaServiceImpl.java
  src/main/java/com/knu/ntttt_server/user/repository/UserArtistRepository.java
Labels: fix

#37 modify: 가챠 정보 반환할때(post 포함) 남은 chance 수도 포함하도록 변경함
  src/main/java/com/knu/ntttt_server/token/controller/GachaTokenController.java
  src/main/java/com/knu/ntttt_server/token/dto/GachaDto.java
  src/main/java/com/knu/ntttt_server/token/service/GachaService.java
  src/main/java/com/knu/ntttt_server/token/service/GachaServiceImpl.java
Labels: modification

#39 fix: 중복된 아티스트 저장 않도록 UserArtist 유니크 추가, 예외처리 추가
  src/main/java/com/knu/ntttt_server/core/response/ResultCode.java
  src/main/java/com/knu/ntttt_server/user/model/UserArtist.java
  src/main/java/com/knu/ntttt_server/user/repository/UserArtistRepository.java
  src/main/java/com/knu/ntttt_server/user/service/UserArtistService.java
Labels: fix

#40 modify: 로그레벨 info이상만 출력하도록 수정, 쿼리 로그 안보이도록 수정
  src/main/resources/application-dev.yml
Labels: modification

#42 fix: token sold out을 예외처리 하지않도록 추가, tokenDto 상태 반환 추가
  src/main/java/com/knu/ntttt_server/core/response/ResultCode.java
  src/main/java/com/knu/ntttt_server/token/dto/TokenDto.java
  src/main/java/com/knu/ntttt_server/token/service/GachaServiceImpl.java
Labels: fix

#43 modify: 그룹, 퍼블리셔 추가
  src/main/java/com/knu/ntttt_server/token/model/Group.java
  src/main/java/com/knu/ntttt_server/token/model/Publisher.java
Labels: modification

#44 fix: 이미 선택했던 아티스트 선택시 예외하지않고 무시하는것으로 변경
  src/main/java/com/knu/ntttt_server/user/service/UserArtistService.java
Labels: fix

#50 fix: 지갑 주소 중복 예외처리 추가
  src/main/java/com/knu/ntttt_server/user/repository/UserRepository.java
  src/main/java/com/knu/ntttt_server/user/service/UserService.java
Labels: fix
